### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hudarui** [ccforward/rubik#1]
我完全按照官网的方法安装,但是npm run dev的时候报错
 ERROR  Failed to compile with 1 errors
This dependency was not found in node_modules:
* i-rubik
查看了node_modules文件夹,的的确确的存在i-rubik这个文件夹
环境
win10 vue-cli webpack

**Comment by hudarui** [comment]
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.v
ue
Module not found: Error: Can't resolve 'i-rubik' in 'D:\gopath\src\github.com\hudarui\vueRub
ik\src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 24:
0-28
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main
.js

**Comment by hudarui** [comment]
我研究了一下,down下来的文件里,package.json里面的main是dist/rubik.min.js,可是我的大哥哥呀,根本没有dist目录,我在这里苦逼了两个小时,求大神赶快修复,我心好累

**Comment by ccforward** [comment]
@hudarui    

你升级到  0.2.4  的版本

上个版本的 .npmignore 文件被被修改了  sorry

**Comment by hudarui** [comment]
谢谢你的答复,我已经直接git 源代码下来了 `[](url)`

**Comment by ccforward** [comment]
@hudarui    刚刚更新了代码  修复了bug   你pull下吧
